### ISSUE TITLE
Normalize 1000-SR.1 data set

### ISSUE THREAD

**Issue by ronaldtse** [ituob/service-publications-data#30]
This task is to normalize the 1000-SR.1 data set into a YAML collection:

```yaml
country:
  en:
    name: Andorra
    status: The telex service is no longer provided
  es:
    name: Andorra
    status: El servicio télex está suprimido
  fr:
    name: Andorre
    status: Le service télex n’est plus assuré.
 
...
```

You will need to obtain data from all three files to complete this:
* `T-SP-SR.1-2012-MSW-E.adoc`
* `T-SP-SR.1-2012-MSW-F.adoc`
* `T-SP-SR.1-2012-MSW-S.adoc`
