### ISSUE TITLE
Script: Reformat dataset/data item/field definitions in meta

### ISSUE THREAD

**Issue by strogonoff** [ituob/service-publications-data#42]
from:

```
T-SP-E.212B-2018.et:
  type: array
  title:
    en: Blablabla Extra-territorial use* of MCC/MNC, Annex E to Recommendation ITU-T E.212
    fr: Utilisation extraterritoriale* du MCC/MNC, Annexe E à la Recommandation UIT-T
      E.212
  locale:
    country_or_area:
      en: Country or Geographical Area
      fr: Pays ou Zone géographique
```

to:

```
T-SP-E.212B-2018.et:
  title:
    en: Blablabla Extra-territorial use* of MCC/MNC, Annex E to Recommendation ITU-T E.212
    fr: Utilisation extraterritoriale* du MCC/MNC, Annexe E à la Recommandation UIT-T
      E.212
  type: array
  item:
    type: object
      fields:
        - id: country_or_area
          label:
            en: Country or Geographical Area
            fr: Pays ou Zone géographique
```
